# AUTOGENERATED! DO NOT EDIT! File to edit: 00_export_v4.ipynb (unless otherwise specified).


__all__ = ['x']


# Cell nr. 185
x = 'hi'


# Cell nr. 186
"This is a tricky case";


# Cell nr. 187
import nbdev_rewrite
from .test import *


# Internal Cell nr. 188
2+2;


# Cell nr. 189
1+1;


# Cell nr. 190
3+3;


# Cell nr. 190
3+3;


# Cell nr. 194
'this is inside a scope'